### ISSUE TITLE
Modify project schema, add connectivity nodes between consumers, DER and ACLineSegments

### ISSUE THREAD

**Issue by dunjabursac** [fgbjoki/DERMS-Master2020#20]

**Comment by fgbjoki** [comment]
[Breaker?](https://ibb.co/KhyztZd)... normalno otvoren breaker ili si ostavila to slucajno?

**Comment by dunjabursac** [comment]
> [Breaker?](https://ibb.co/KhyztZd)... normalno otvoren breaker ili si ostavila to slucajno?

Slučajno... Je l' sada to ok?
Naravno, nije još gotova šema.

**Comment by fgbjoki** [comment]
> > [Breaker?](https://ibb.co/KhyztZd)... normalno otvoren breaker ili si ostavila to slucajno?
> 
> Slučajno... Je l' sada to ok?
> Naravno, nije još gotova šema.

Nisam siguran da li su to dva povezana terminala ili nesto drugo, sto se mene tice ja bih te dve tacke uklonio i tu "liniju" nazvao ACLineSegmentX i ostatak je ACLineSegmentX_1 ili _Part1 nisam siguran kako cemo treba da se dogovorimo.
