### ISSUE TITLE
ACLineSegment name vote

### ISSUE THREAD

**Issue by fgbjoki** [fgbjoki/DERMS-Master2020#21]
Da se usaglasimo sa semom posto cemo je verovatno svi zajedno kucati.
ACLineSegment se sastoji iz vise delova, za koji format CIMXML-a biste se opredelili?
ACLineSemgnetX_PartY ili ACLineSegmentX_Y?

**Comment by fgbjoki** [comment]
Ja sam za drugu varijantu.

**Comment by dunjabursac** [comment]
druga opcija - bez "Part"

**Comment by JovanDavidovic** [comment]
I ja sam vise za drugu opciju

**Comment by fgbjoki** [comment]
Prilikom kucanja CIMXML-a koristicemo drugu opciju - ACLineSegmentX_Y.
