### ISSUE TITLE
`var client = ...`

### ISSUE THREAD

**Issue by fgbjoki** [fgbjoki/DERMS-Master2020#3]
`var client = ...`

_Originally posted by @sstefan1 in https://github.com/fgbjoki/DERMS-Master2020/pull/2#discussion_r535205991_

Manje vise cackam GitHub, ako ovaj Issue moze da se izglasa za jedan ili drugi nacin pisanja koda.

**Comment by sstefan1** [comment]
var :)

**Comment by fgbjoki** [comment]
idemo var :D
